.TH Nao 1 nao\-git
.SH NAME
nao \- cli space repetition flashcard program
.SH SYNOPSIS
.B nao
\fIcommand\fR [\fIDECK\fR]
.SH DESCRIPTION
Some description of the program
.SH COMMANDS
Underlined arguments to the following commands are mandatory. Square brackets represent that multiple arguments can be fed to the command.
.TP
\fBadd\fR \fIDECK\fR
Add a new flashcard to \fIDECK\fR. If \fIDECK\fR does not exists yet it will be created.
.TP
\fBreview\fR [\fIDECK\fR]
Review [\fIDECK\fR] in the given order.
.TP
\fBcram\fR [\fIDECK\fR]
Cram (study all flashcards) [\fIDECK\fR] in the given order.
.TP
\fBinfo\fR \fIDECK\fR
Display informations about \fIDECK\fR.
.SH CONFIG
Notes on the config file.
.SH AUTHOR
Written by Gabriele Rastello.
.SH REPORTING BUGS
Github repository: <https://github.com/gRastello/nao>
